import os

SECRET_KEY = 'you_guess'
DEBUG = True

DB_USERNAME = 'hehemama00'
DB_PASSWORD = ''
BLOG_DATABASE_NAME = 'myblog'
DB_HOST = os.getenv('IP', '0.0.0.0')
DB_URI = 'mysql+pymysql://{}:{}@{}/{}'.format(DB_USERNAME, DB_PASSWORD, DB_HOST, BLOG_DATABASE_NAME)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True